version: "3.9"

services:
  web1:
    image: jmalloc/echo-server:latest
    hostname: web1
    container_name: web1
    networks:
      - network1

  web2:
    image: jmalloc/echo-server:latest
    hostname: web2
    container_name: web2
    networks:
      - network1

  web3:
    image: jmalloc/echo-server:latest
    hostname: web3
    container_name: web3
    networks:
      - network1

  haproxy:
    image: haproxytech/haproxy-alpine:2.7.2
    hostname: haproxy
    container_name: haproxy
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    ports:
      - "80:80"
      - "8404:8404"
    expose:
      - "80"
      - "8404:8404"
    networks:
      - network1

networks:
  network1:
    driver: bridge
