version: "3.9"

services:
  web1:
    image: jmalloc/echo-server:latest
    hostname: web1
    networks:
      - network1

  web2:
    image: jmalloc/echo-server:latest
    hostname: web2
    networks:
      - network1

  web3:
    image: jmalloc/echo-server:latest
    hostname: web3
    networks:
      - network1

  haproxy:
    image: haproxytech/haproxy-alpine:2.7.2
    hostname: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/
    ports:
      - "80:80"
      - "8404:8404"
    networks:
      - network1

networks:
  network1:
    driver: bridge
