version: "3.9"

services:
  web1:
    image: jmalloc/echo-server:latest
    networks:
      - network1

  web2:
    image: jmalloc/echo-server:latest
    networks:
      - network1

  web3:
    image: jmalloc/echo-server:latest
    networks:
      - network1

  haproxy:
    hostname: haproxy
    build:
      context: .
      dockerfile: haproxy/Dockerfile
    networks:
      - network1

networks:
  network1:
    driver: bridge
